# Site settings
title: Cayu
email: rockaxel@gmail.com
description: Web craftmen
url: https://cayu.io # the base hostname & protocol for your site
# twitter_username: nineties_panda
github_username: cayu-io
# instagram_username: axel.rock

# Build settings
markdown: kramdown
permalink: /:categories/:title/
include:
  - _pages
exclude:
  - Gemfile
  - Gemfile.lock
gems:
  - jekyll/tagging
  - jekyll-seo-tag

defaults:
-
  scope:
    path: ""
    type: pages
  values:
    layout: page
-
  scope:
    path: ""
    type: posts
  values:
    layout: post
    author: axel
-
  scope:
    path: ""
    type: drafts
  values:
    layout: post

# SASS
sass:
  sass_dir: _sass
  style:   :compressed

# Tags
tag_page_layout: tag_page
tag_page_dir: tag
tag_permalink_style: pretty

authors:
  axel:
    name: Axel Rock
    display_name: Axel
    bio: Salut, moi c’est Axel, bidouilleur numérique. D’après mon diplôme de l’école des Gobelins, je suis officiellement Concepteur Réalisateur Multimédia. Dans les faits, je suis spécialisé dans le développement de sites web et applications en tout genre. Mais je m’intéresse aussi beaucoup à la photo, la vidéo, le design et l’écriture.
    gravatar: /images/avatar/axel.jpg
    email: rockaxel@gmail.com
    web: http://axelrock.fr
    twitter: nineties_panda
    github: axel-rock
    instagram: axel.rock